### ISSUE TITLE
selenium exception during last.fm login

### ISSUE THREAD

**Issue by eriwst** [TheKingElessar/Unscrobbler#1] opened 2022-02-02 16:07 UTC
Unfortunately I get the following error:

```
Launching Firefox
Traceback (most recent call last):
  File "/Users/eric/dev/Unscrobbler/./Unscrobbler.py", line 136, in <module>
    driver.find_element(by = By.CSS_SELECTOR, value = "button[name='submit']").click()
  File "/Users/eric/.venv/unscrobbler/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 81, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Users/eric/.venv/unscrobbler/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 710, in _execute
    return self._parent.execute(command, params)
  File "/Users/eric/.venv/unscrobbler/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/Users/eric/.venv/unscrobbler/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <button class="btn-primary" name="submit" type="submit"> is not clickable at point (497,443) because another element <div class="onetrust-pc-dark-filter ot-fade-in"> obscures it
Stacktrace:
WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:183:5
ElementClickInterceptedError@chrome://remote/content/shared/webdriver/Errors.jsm:282:5
webdriverClickElement@chrome://remote/content/marionette/interaction.js:166:11
interaction.clickElement@chrome://remote/content/marionette/interaction.js:125:11
clickElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.jsm:203:24
receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.jsm:91:31
```

**Comment by TheNathanSpace** [comment] 2022-02-02 17:27
The problem is with this line, line 136:
```
    driver.find_element(by = By.CSS_SELECTOR, value = "button[name='submit']").click()
```

Apparently the timing isn't working right in your case.

If you can open the file in a text editor, paste this in right **before** that line, save it, then try running it again, that might help:
```
    from selenium.webdriver.support import expected_conditions
    from selenium.webdriver.support.wait import WebDriverWait
    WebDriverWait(driver, 10).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "button[name='submit']")))
```

That should make it wait until it's able to click the button.

You can also download the new `Unscrobbler.py` file, which has the change: https://raw.githubusercontent.com/TheKingElessar/Unscrobbler/master/Unscrobbler.py

**Comment by eriwst** [comment] 2022-02-02 20:08
Thank you for your response,

I updated the code but still got this error message:

```
Launching Firefox
Traceback (most recent call last):
  File "/Users/eric/dev/Unscrobbler/./Unscrobbler.py", line 140, in <module>
    driver.find_element(by = By.CSS_SELECTOR, value = "button[name='submit']").click()
  File "/Users/eric/.venv/unscrobbler/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 81, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Users/eric/.venv/unscrobbler/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 710, in _execute
    return self._parent.execute(command, params)
  File "/Users/eric/.venv/unscrobbler/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/Users/eric/.venv/unscrobbler/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <button class="btn-primary" name="submit" type="submit"> is not clickable at point (497,443) because another element <div class="onetrust-pc-dark-filter ot-fade-in"> obscures it
Stacktrace:
WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:183:5
ElementClickInterceptedError@chrome://remote/content/shared/webdriver/Errors.jsm:282:5
webdriverClickElement@chrome://remote/content/marionette/interaction.js:166:11
interaction.clickElement@chrome://remote/content/marionette/interaction.js:125:11
clickElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.jsm:203:24
receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.jsm:91:31
```

**Comment by TheNathanSpace** [comment] 2022-02-02 22:50
Ah, I see the problem, it's giving you a prompt to accept cookies.

This should be fixed now by giving you a chance to accept the cookies popup. Download the new `Unscrobbler.py` file, which has the fix: https://raw.githubusercontent.com/TheKingElessar/Unscrobbler/master/Unscrobbler.py

When you run it, the program will pause on the login screen until you accept the cookies prompt by clicking in the browser window.

Please let me know if this solves it!

**Comment by eriwst** [comment] 2022-02-03 08:29
Hello, 
You were right, it is because of the cookie dialog. The script works now. Could you also automate the acceptance of cookies?

Thank you!

**Comment by TheNathanSpace** [comment] 2022-02-03 17:48
Glad it works! Thanks for reporting the bug. :)

Automating the acceptance would be good, but I just can't get the prompt to pop up on my device to test it! Using different browsers or clearing cookies just isn't working. I'll have to spend some more time on it.

**Closed as completed by TheNathanSpace** 2022-02-03 17:48 UTC
